name: Build Firmwarem

on:
  push:
    branches:
      - main

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone repository
        run: ls
